[project]
name = "Health Planner Agent"
run = "main.py"
enable_telemetry = true  # Whether to enable telemetry (default: true). No personal data is collected.
user_env = []  # List of environment variables to be provided by each user to use the app.
session_timeout = 3600  # Duration (in seconds) during which the session is saved when the connection is lost
user_session_timeout = 1296000  # 15 days
cache = false  # Enable third parties caching (e.g., LangChain cache)
allow_origins = ["*"]  # Authorized origins

[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
sample_rate = 24000

[features.mcp.sse]
enabled = true

[features.mcp.stdio]
enabled = true
allowed_executables = [ "npx", "uvx" ]

[UI]
name = "Assistant"
description = "Your personalized Health & Wellness AI Companion"
default_theme = "dark"
cot = "full"

[meta]
generated_by = "2.5.5"
